CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    url VARCHAR(512) UNIQUE NOT NULL,
    code VARCHAR (8) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    click_count BIGINT NOT NULL DEFAULT 0
)

-- CREATE INDEX IF NOT EXISTS idx_url ON urls(url)
CREATE INDEX IF NOT EXISTS idx_code ON urls(code)