services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_v3
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    healthcheck:
      # test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      test: ["CMD", "/app/main", "-check-health"] 
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres_database
    environment:
      - POSTGRES_DB=url_shortener_v3
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./migration:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536
    tmpfs:
      - /tmp:size=128M,uid=70,gid=70,mode=1777
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge